/*
 * oled_font.h - font tables for the SSD1306 menu project
 *
 * AUTO-GENERATED by tools/genfont.ps1 - do not edit by hand.
 * ASCII : 8x16, SimSun half-width forms, index = ascii - 0x20  (95 glyphs)
 * CJK   : 16x16, SimSun, looked up by Unicode code point
 *
 * Storage order is native SSD1306 page order: byte k of a glyph is one
 * column, bit 0 = topmost row of that 8-row page.  A 16x16 glyph is
 * bytes[0..15] = page N (rows 0..7) then bytes[16..31] = page N+1.
 * Strings are arrays of Unicode code points, so the source files stay
 * pure ASCII and never depend on the editor/compiler text encoding.
 */

#ifndef __OLED_FONT_H
#define __OLED_FONT_H

#include <stdint.h>

#define FONT_ASCII_FIRST  0x20u
#define FONT_ASCII_LAST   0x7Eu
#define FONT_ASCII_COUNT  95u
#define FONT_CJK_COUNT    71u

/* Unicode code points of every CJK glyph in the table */
#define CN_ZHU     0x4E3Bu   /* zhu    = main / host */
#define CN_YU      0x4E8Eu   /* yu     = at / to */
#define CN_JIAO    0x4EA4u   /* jiao   = alternate */
#define CN_LIANG   0x4EAEu   /* liang  = bright */
#define CN_CHUAN   0x4F20u   /* chuan  = transmit */
#define CN_XIN     0x4FE1u   /* xin    = information */
#define CN_TING    0x505Cu   /* ting   = stop */
#define CN_GUANG   0x5149u   /* guang  = light */
#define CN_GUAN    0x5173u   /* guan   = close / about */
#define CN_ZHI     0x5236u   /* zhi    = make */
#define CN_GONG    0x529Fu   /* gong   = function */
#define CN_DONG    0x52A8u   /* dong   = move */
#define CN_DAN     0x5355u   /* dan    = list / sheet */
#define CN_HAO     0x53F7u   /* hao    = number */
#define CN_MING2   0x540Du   /* ming   = name */
#define CN_QI      0x542Fu   /* qi     = start */
#define CN_QI2     0x5668u   /* qi     = device */
#define CN_HUI     0x56DEu   /* hui    = back */
#define CN_FU      0x590Du   /* fu     = again */
#define CN_XING2   0x59D3u   /* xing   = surname */
#define CN_XUE     0x5B66u   /* xue    = study */
#define CN_ZHAN    0x5C55u   /* zhan   = spread */
#define CN_XUN     0x5DE1u   /* xun    = patrol */
#define CN_DU      0x5EA6u   /* du     = degree / level */
#define CN_KAI     0x5F00u   /* kai    = open / on */
#define CN_SHI2    0x5F0Fu   /* shi    = style / type */
#define CN_TAI     0x6001u   /* tai    = condition */
#define CN_HUI2    0x6062u   /* hui    = restore */
#define CN_XI      0x606Fu   /* xi     = breath / news */
#define CN_GAN     0x611Fu   /* gan    = sense */
#define CN_DA      0x6253u   /* da     = hit / open */
#define CN_TUO     0x62D3u   /* tuo    = expand */
#define CN_AN      0x6309u   /* an     = press */
#define CN_KONG    0x63A7u   /* kong   = control */
#define CN_SHI3    0x65F6u   /* shi    = time */
#define CN_XIAN    0x663Eu   /* xian   = show */
#define CN_TI      0x66FFu   /* ti     = substitute */
#define CN_BEN     0x672Cu   /* ben    = this */
#define CN_JI      0x673Au   /* ji     = machine */
#define CN_MO      0x6A21u   /* mo     = model / mode */
#define CN_ZHI2    0x6B62u   /* zhi    = halt */
#define CN_CE      0x6D4Bu   /* ce     = measure */
#define CN_YAN     0x6F14u   /* yan    = perform / demo */
#define CN_MIE     0x706Du   /* mie    = extinguish / off */
#define CN_SHUO    0x70C1u   /* shuo   = sparkle */
#define CN_PIAN    0x7247u   /* pian   = piece / chip */
#define CN_BAN     0x7248u   /* ban    = version */
#define CN_ZHUANG  0x72B6u   /* zhuang = state */
#define CN_SHI     0x793Au   /* shi    = show */
#define CN_XI2     0x7CFBu   /* xi     = system */
#define CN_XIAN2   0x7EBFu   /* xian   = line */
#define CN_TONG    0x7EDFu   /* tong   = whole */
#define CN_ZHI3    0x7F6Eu   /* zhi    = place / set */
#define CN_BEI     0x80CCu   /* bei    = back */
#define CN_NENG    0x80FDu   /* neng   = ability */
#define CN_XIN2    0x82AFu   /* xin    = chip core */
#define CN_CAI     0x83DCu   /* cai    = dish / menu */
#define CN_FENG    0x8702u   /* feng   = bee / buzzer */
#define CN_XING    0x884Cu   /* xing   = walk / run */
#define CN_REN     0x8BA4u   /* ren    = recognise */
#define CN_SHE     0x8BBEu   /* she    = set up */
#define CN_SHI4    0x8BD5u   /* shi    = try / test */
#define CN_YUN     0x8FD0u   /* yun    = run */
#define CN_FAN     0x8FD4u   /* fan    = return */
#define CN_JIAN2   0x952Eu   /* jian   = key */
#define CN_SHAN    0x95EAu   /* shan   = flash */
#define CN_BI      0x95EDu   /* bi     = close */
#define CN_JIAN    0x95F4u   /* jian   = between */
#define CN_PIN     0x9891u   /* pin    = frequency */
#define CN_MING    0x9E23u   /* ming   = cry / beep */
#define CN_MO2     0x9ED8u   /* mo     = silent / default */

extern const uint8_t font_ascii_8x16[FONT_ASCII_COUNT][16];
extern const uint16_t font_cjk_code[FONT_CJK_COUNT];
extern const uint8_t font_cjk_16x16[FONT_CJK_COUNT][32];

/* returns glyph index, or -1 when the character has no bitmap */
int Font_FindCjk(uint16_t code);

#endif /* __OLED_FONT_H */

